language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_c3e2d673b285_key -iv $encrypted_c3e2d673b285_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
